version: "3"

volumes:
  db-data:

services:
  db:
    image: postgres:14
    container_name: mini-chat-chat-db
    volumes:
      - db-data:/var/lib/postgresql/mini_chat_gpt_db/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password